#include "backend.h"
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QLocalSocket>
#include <QProcessEnvironment>
#include <QProcess>
#include <QStandardPaths>
#include <QDesktopServices>
#include <QUrl>
#include <QLoggingCategory>
#include <QDir>
#include <QUuid>
#include <QCoreApplication>
#include <QEvent>

Q_LOGGING_CATEGORY(uiLog, "thinpi.launcher")

Backend::Backend(QObject *parent):QObject(parent){const auto env=QProcessEnvironment::systemEnvironment();m_devMode=env.value("THINPI_DEV_MODE")=="1";m_apiUrl=env.value("THINPI_API_URL",m_devMode?"http://127.0.0.1:8080":"https://thinpi.internal");m_agentSocket=env.value("THINPI_AGENT_SOCKET","/run/thinpi/agent.sock");m_deviceIdentifier=env.value("THINPI_DEVICE_ID",m_devMode?"dev-device":"");m_poll.setInterval(800);m_idle.setSingleShot(true);connect(&m_poll,&QTimer::timeout,this,&Backend::pollAgent);connect(&m_idle,&QTimer::timeout,this,&Backend::logout);QCoreApplication::instance()->installEventFilter(this);if(m_deviceIdentifier.isEmpty())agentRequest({{"action","status"}},[this](QJsonObject x){m_deviceIdentifier=x["device_identifier"].toString();});}
bool Backend::eventFilter(QObject *watched,QEvent *event){if(!m_token.isEmpty()&&(event->type()==QEvent::KeyPress||event->type()==QEvent::MouseButtonPress||event->type()==QEvent::TouchBegin))armIdleLock();return QObject::eventFilter(watched,event);}
void Backend::armIdleLock(){if(!m_token.isEmpty())m_idle.start(m_isAdmin?300000:1800000);}
void Backend::clearLocalSession(){m_token.clear();m_displayName.clear();m_isAdmin=false;m_connections.clear();m_restrictionMessage.clear();m_poll.stop();m_idle.stop();emit restrictionMessageChanged();emit isAdminChanged();emit displayNameChanged();setView("login");}
void Backend::setView(QString x){if(m_view==x)return;qCInfo(uiLog)<<"view transition"<<m_view<<"to"<<x;m_view=std::move(x);emit viewChanged();}
void Backend::setBusy(bool x){if(m_busy==x)return;m_busy=x;emit busyChanged();}
void Backend::fail(const QString &message,bool offline){m_error=message;emit errorMessageChanged();setBusy(false);setView(offline?"offline":(m_token.isEmpty()?"login":"dashboard"));}
void Backend::dismissError(){m_error.clear();emit errorMessageChanged();}
void Backend::retry(){dismissError();if(m_token.isEmpty())setView("login");else loadConnections();}
void Backend::controllerRequest(const QByteArray &method,const QString &path,const QJsonObject &body,std::function<void(QJsonObject)> ok){QNetworkRequest request(QUrl(m_apiUrl+path));request.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");if(!m_token.isEmpty())request.setRawHeader("Authorization",QByteArray("Bearer ")+m_token.toUtf8());QNetworkReply *reply=nullptr;const auto data=QJsonDocument(body).toJson(QJsonDocument::Compact);if(method=="GET")reply=m_network.get(request);else if(method=="POST")reply=m_network.post(request,data);else reply=m_network.sendCustomRequest(request,method,data);connect(reply,&QNetworkReply::finished,this,[this,reply,ok=std::move(ok)](){const auto bytes=reply->readAll();const auto status=reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();const auto err=reply->error();reply->deleteLater();QJsonParseError pe;const auto doc=QJsonDocument::fromJson(bytes,&pe);if(err!=QNetworkReply::NoError||status<200||status>=300){QString message="ThinPi Controller is unavailable. Check the network and try again.";bool offline=status==0;if(doc.isObject()){const auto safe=doc.object()["error"].toObject()["message"].toString();if(!safe.isEmpty()){message=safe;offline=false;}}if(status==401)clearLocalSession();fail(message,offline);return;}ok(doc.object());});}
void Backend::login(const QString &username,const QString &password){if(username.trimmed().isEmpty()||password.isEmpty()){fail("Enter your username and password.");return;}dismissError();setBusy(true);controllerRequest("POST","/api/v1/auth/login",{{"username",username.trimmed()},{"password",password}},[this](QJsonObject x){m_token=x["token"].toString();const auto user=x["user"].toObject();m_displayName=user["display_name"].toString();m_isAdmin=user["is_admin"].toBool();emit displayNameChanged();emit isAdminChanged();armIdleLock();loadConnections();});}
void Backend::loadConnections(){setBusy(true);controllerRequest("GET","/api/v1/connections",{},[this](QJsonObject x){m_connections.replace(x["items"].toArray());const auto policy=x["policy"].toObject();const auto message=policy["allowed"].toBool(true)?QString{}:policy["reason"].toString();if(message!=m_restrictionMessage){m_restrictionMessage=message;emit restrictionMessageChanged();}setBusy(false);setView("dashboard");});}
void Backend::refresh(){if(!m_token.isEmpty())loadConnections();}
void Backend::logout(){if(!m_token.isEmpty())controllerRequest("POST","/api/v1/auth/logout",{},[](QJsonObject){});clearLocalSession();setBusy(false);dismissError();}
void Backend::openAdministration(){if(!m_isAdmin||m_token.isEmpty())return;dismissError();setBusy(true);controllerRequest("POST","/api/v1/admin-handoff",{},[this](QJsonObject x){const QUrl url=QUrl(m_apiUrl).resolved(QUrl(x["path"].toString()));bool opened=false;if(m_devMode){opened=QDesktopServices::openUrl(url);}else if(!m_adminBrowser){const auto configured=QProcessEnvironment::systemEnvironment().value("THINPI_ADMIN_BROWSER");QString browser=configured;if(browser.isEmpty()){for(const auto &candidate: {QStringLiteral("chromium"),QStringLiteral("google-chrome-stable"),QStringLiteral("chromium-browser")}){browser=QStandardPaths::findExecutable(candidate);if(!browser.isEmpty())break;}}if(!browser.isEmpty()){const auto cacheRoot=QStandardPaths::writableLocation(QStandardPaths::CacheLocation);m_adminProfile=cacheRoot+QStringLiteral("/admin-")+QUuid::createUuid().toString(QUuid::WithoutBraces);QDir().mkpath(m_adminProfile);m_adminBrowser=new QProcess(this);m_adminBrowser->setProgram(browser);m_adminBrowser->setArguments({QStringLiteral("--kiosk"),QStringLiteral("--app=")+url.toString(),QStringLiteral("--user-data-dir=")+m_adminProfile,QStringLiteral("--no-first-run"),QStringLiteral("--no-default-browser-check"),QStringLiteral("--noerrdialogs"),QStringLiteral("--disable-session-crashed-bubble"),QStringLiteral("--disable-background-networking"),QStringLiteral("--disable-component-update"),QStringLiteral("--disable-sync"),QStringLiteral("--disable-translate"),QStringLiteral("--disable-pinch"),QStringLiteral("--disable-extensions"),QStringLiteral("--disable-plugins"),QStringLiteral("--disable-pdf-extension"),QStringLiteral("--password-store=basic"),QStringLiteral("--overscroll-history-navigation=0")});connect(m_adminBrowser,qOverload<int,QProcess::ExitStatus>(&QProcess::finished),this,[this](){QDir(m_adminProfile).removeRecursively();m_adminProfile.clear();m_adminBrowser->deleteLater();m_adminBrowser=nullptr;});m_adminBrowser->start();opened=m_adminBrowser->waitForStarted(3000);if(!opened){QDir(m_adminProfile).removeRecursively();m_adminProfile.clear();m_adminBrowser->deleteLater();m_adminBrowser=nullptr;}}}setBusy(false);if(!opened)fail("The locked administration browser is unavailable on this ThinPi.");});}
void Backend::openMaintenance(){if(!m_isAdmin||m_token.isEmpty()||m_deviceIdentifier.isEmpty())return;dismissError();setBusy(true);controllerRequest("POST","/api/v1/maintenance",{{"device_identifier",m_deviceIdentifier}},[this](QJsonObject x){agentRequest({{"action","maintenance"},{"ticket",x["ticket"].toString()}},[this](QJsonObject response){setBusy(false);if(!response["accepted"].toBool()){fail("Local maintenance could not be authorised.");return;}logout();});});}
void Backend::launch(int row){const auto id=m_connections.idAt(row);if(id==0)return;if(!m_restrictionMessage.isEmpty()){fail(m_restrictionMessage);return;}if(m_deviceIdentifier.isEmpty()){fail("The local ThinPi service is unavailable.");return;}m_activeName=m_connections.nameAt(row);m_activeProtocol=m_connections.protocolAt(row).toUpper();m_sessionMessage="Connecting to "+m_activeName+QStringLiteral("…");emit sessionMessageChanged();setBusy(true);setView("session");controllerRequest("POST",QString("/api/v1/connections/%1/launch").arg(id),{{"device_identifier",m_deviceIdentifier}},[this](QJsonObject x){agentRequest({{"action","launch"},{"ticket",x["ticket"].toString()}},[this](QJsonObject response){if(!response["accepted"].toBool()){fail("The local ThinPi service could not start the session.");return;}m_seenActive=true;setBusy(false);m_poll.start();pollAgent();});});}
void Backend::agentRequest(const QJsonObject &request,std::function<void(QJsonObject)> complete){auto *socket=new QLocalSocket(this);auto *timeout=new QTimer(socket);timeout->setSingleShot(true);timeout->setInterval(3000);connect(timeout,&QTimer::timeout,socket,[this,socket](){socket->abort();socket->deleteLater();if(m_view=="session")fail("The local ThinPi service is unavailable.");});connect(socket,&QLocalSocket::connected,socket,[socket,request](){socket->write(QJsonDocument(request).toJson(QJsonDocument::Compact)+"\n");socket->flush();});connect(socket,&QLocalSocket::readyRead,socket,[socket,timeout,complete=std::move(complete),buffer=QByteArray{}]()mutable{buffer+=socket->readAll();if(!buffer.contains('\n'))return;const auto doc=QJsonDocument::fromJson(buffer);if(!doc.isObject())return;timeout->stop();complete(doc.object());socket->disconnectFromServer();socket->deleteLater();});socket->connectToServer(m_agentSocket,QIODevice::ReadWrite);timeout->start();}
void Backend::pollAgent(){agentRequest({{"action","status"}},[this](QJsonObject response){const auto status=response["status"].toObject();const auto state=status["state"].toString();if(state!="idle")m_seenActive=true;if(state=="active"){m_sessionMessage=m_activeName+" — "+m_activeProtocol;emit sessionMessageChanged();}if(state=="error"){m_poll.stop();const auto detail=status["last_error"].toString();fail(detail.isEmpty()?"Unable to connect to "+m_activeName+".":detail);}else if(state=="idle"&&m_seenActive){m_poll.stop();m_sessionMessage.clear();emit sessionMessageChanged();setView("dashboard");}});}
void Backend::endSession(){agentRequest({{"action","cancel"}},[](QJsonObject){});}
